### ISSUE TITLE
Need to add a feature Text alignment

### ISSUE THREAD

**Issue by MohammedAkramU7** [ahmedkaludi/Easy-Table-of-Contents#409]
Ref ticket:- https://magazine3.in/conversation/93578?folder_id=21

Description:-
User want a text alignment inside the table.

Example screenshot:-
https://prnt.sc/6wBmkyiN5dDm

**Comment by muslimakhan** [comment]
For now, issue is resolved on user end through below css code:
```CSS
#ez-toc-container nav {
    text-align: left;
}
```
@Sanjeevsetu sir, we can add this feature according to need through our plugin too.
