### ISSUE TITLE
When the sticky toggle options are enabled, the other content gets hidden from the TOC.

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/Easy-Table-of-Contents#439]
We have created a functionality where, when users enable the sticky toggle options, the other content gets hidden on the website. The TOC should automatically close when users click on the heading of the TOC and it scrolls to the heading.

2. The Cancel TOC toggle option does not appear on the user's website.

https://prnt.sc/NFrOriPUsFWl 

Ref ticket: https://magazine3.in/conversation/119304?folder_id=29

**Comment by muslimakhan** [comment]
2. The Cancel TOC toggle option does not appear on the user's website.
Reply: For second point, this issue is faced on user end, it will be resolved from this below CSS:
```CSS
.ez-toc-sticky-fixed .ez-toc-sidebar .ez-toc-sticky-title-container {
       width: 90%;
}
```
User can add from Customization Theme Site => Additional CSS or Theme Editor from WP Admin.
